In [ ]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

In [2]:
df = pd.read_csv("FinalProfessionalPlayersDataset.txt")

C:\Users\Dell\AppData\Local\Temp\ipykernel_27072\3399175749.py:1: DtypeWarning: Columns (50,51,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("FinalProfessionalPlayersDataset.txt")

In [3]:
df.head()

,gameId,team,summoner,region,champion,timestamp,coordinate_x,coordinate_y,level,minionsKilled,...,trueDamageDoneToChampions,trueDamageTaken,victory,eventType,skillSlot,buildingType,lane,monster,itemName,role
0,EUW1_6272362521,Blue,anonymous 2,euw1,Akshan,0.000000,554.0,581.0,1.0,0.0,...,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,TOP
1,EUW1_6272362521,Blue,anonymous 2,euw1,Akshan,1.000300,3177.0,8848.0,1.0,0.0,...,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,TOP
2,EUW1_6272362521,Blue,anonymous 2,euw1,Akshan,2.000733,2665.0,13301.0,1.0,2.0,...,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,TOP
3,EUW1_6272362521,Blue,anonymous 2,euw1,Akshan,1.932467,NaN,NaN,NaN,NaN,...,NaN,NaN,False,SkillLevelUp,1.0,NaN,NaN,NaN,NaN,TOP
4,EUW1_6272362521,Blue,anonymous 2,euw1,Akshan,3.001000,3352.0,13461.0,3.0,14.0,...,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,TOP

In [9]:
df['role'].unique()

array(['TOP', 'JUNGLE', 'MIDDLE', 'BOTTOM', 'UTILITY'], dtype=object)

In [4]:
df.shape

(392071, 55)

In [5]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
392066    False
392067    False
392068    False
392069    False
392070    False
Length: 392071, dtype: bool

In [7]:
df.isnull().sum()

gameId                                0
team                                  0
summoner                              0
region                                0
champion                              0
timestamp                             0
coordinate_x                     174453
coordinate_y                     174453
level                            261168
minionsKilled                    261168
jungleMinionsKilled              261168
currentGold                      261168
goldPerSecond                    261168
totalGold                        261168
xp                               261168
abilityPower                     261168
armor                            261168
armorPen                         261168
armorPenPercent                  261168
attackDamage                     261168
attackSpeed                      261168
ccReduction                      261168
health                           261168
healthMax                        261168
healthRegen                      261168
lifesteal                        261168
magicPen                         261168
magicPenPercent                  261168
magicResist                      261168
movementSpeed                    261168
omnivamp                         261168
power                            261168
powerMax                         261168
powerRegen                       261168
spellVamp                        261168
magicDamageDone                  261168
magicDamageDoneToChampions       261168
magicDamageTaken                 261168
physicalDamageDone               261168
physicalDamageDoneToChampions    261168
physicalDamageTaken              261168
totalDamageDone                  261168
totalDamageDoneToChampions       261168
totalDamageTaken                 261168
trueDamageDone                   261168
trueDamageDoneToChampions        261168
trueDamageTaken                  261168
victory                               0
eventType                        130903
skillSlot                        325915
buildingType                     381296
lane                             381296
monster                          377488
itemName                         283774
role                                  0
dtype: int64

In [42]:
test = pd.DataFrame(data=df['gameId'].unique(), columns=[df.columns[df.columns.get_loc('gameId')]])
test

               gameId
0     EUW1_6272362521
1     EUW1_6272332377
2     EUW1_6271940279
3     EUW1_6270844496
4     EUW1_6270805157
...               ...
3941    KR_6376023042
3942    KR_6376046864
3943    KR_6376025758
3944    KR_6376000151
3945    KR_6375939420

[3946 rows x 1 columns]